# Generated by Django 3.1.7 on 2021-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
